/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/WawaOffice.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import gsap from "gsap";

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/WawaOffice.glb')
  const ref = useRef();
  const timeLine = useRef();
  const librairyRef = useRef();
  const atticRef = useRef();

  const scroll = useScroll();

  useFrame(() => {
    timeLine.current.seek(scroll.offset * timeLine.current.duration());
  });

  useLayoutEffect(() => {
    timeLine.current = gsap.timeline();

    //Vertical Animation
    timeLine.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    );

    // Whole Office Rotation
    timeLine.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: Math.PI / 6, z: 0 },
      0
    );
    timeLine.current.to(
      ref.current.rotation,
      { duration: 1, x: 0, y: -Math.PI / 6, z: 0 },
      1
    );

    // Whole Office movement
    timeLine.current.to(
      ref.current.position,
      {
        duration: 1,
        x: -1,
        z: 2,
      },
      0
    );
    timeLine.current.to(
      ref.current.position,
      {
        duration: 1,
        x: 1,
        z: 2,
      },
      1
    );

    //Librairy floor
    timeLine.current.from(
      librairyRef.current.position,
      {
        duration: 0.5,
        x: -2,
      },
      0.5
    );
    timeLine.current.from(
      librairyRef.current.rotation,
      {
        duration: 0.5,
        y: -Math.PI / 2,
      },
      0
    );

    //Attic floor
    timeLine.current.from(
      atticRef.current.position,
      {
        duration: 1.5,
        y: 2,
      },
      0
    );
    timeLine.current.from(
      atticRef.current.rotation,
      {
        duration: 0.5,
        y: -Math.PI / 2,
      },
      1
    );
    timeLine.current.from(
      atticRef.current.position,
      {
        duration: 0.5,
        z: -2,
      },
      1.5
    );
  }, [])

  return (
    <group {...props} dispose={null} ref={ref} position={[0.5, -1, -1]}>
      <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
      <group position={[0, 2.114, -2.23]}>
        <group ref={librairyRef}>
          <mesh geometry={nodes['02_library'].geometry} material={materials['02']} />
        </group>
      </group>
      <group position={[-1.97, 4.227, -2.199]}>
        <group ref={atticRef}>
          <mesh geometry={nodes['03_attic'].geometry} material={materials['03']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/WawaOffice.glb')
